### PR TITLE
Enable Win32 build

### PR DESCRIPTION
**Pull request by lgeiger**
Just messing around with appveyor.

Whats the difference between `x86` and `Win32`?

### CODE REVIEW

**Comment by rgbkrk** [comment]
Win32 encompasses more than just x86 (technically it can target ARM as well, which is not relevant to us). It's really the Win32 API that it's targeting. That being said, I think we can give this a go.

**Comment by rgbkrk** [comment]
Then again, maybe we can't based on the current binding - it typecasts from `int64_t` to `int` on... Oh wait a second, we're getting the [same warning on the 64-bit builds too](https://ci.appveyor.com/project/rgbkrk/zmq-prebuilt/build/1.0.106/job/w0ub7pympm4cdim3#L29):

```
..\binding.cc(676): warning C4244: 'argument': conversion from 'int64_t' to 'const int', possible loss of data [C:\projects\zmq-prebuilt\build\zmq.vcxproj]
```

**Comment by rgbkrk** [comment]
I'm of the opinion that we don't have to support 32-bit unless we have a critical mass of users that need it. However, I think we can go ahead and merge this and see how it goes.

**Comment by lgeiger** [comment]
I'm pretty sure there are still even windows 10 32-bit versions out there. Would that mean they cannot use the prebuilds?

**Comment by rgbkrk** [comment]
Wow, I did not realize that [Microsoft changed gears to support 32-bit again](http://www.tweaktown.com/news/42852/microsofts-windows-10-feature-32-bit-version/index.html).

> Would that mean they cannot use the prebuilds?

Yes, if we only do 64-bit.

That being said, I merged this and we can try it all out.

**Pull request merged**
