### PR TITLE
[WIP] Add prebuilt libzmq for unix

### PR DESCRIPTION
**Pull request by lgeiger**
Lets see what travis thinks.

### CODE REVIEW

**Comment by lgeiger** [comment]
Looks like this isn't that easy. I'll give it another shot next week.

**Comment by lgeiger** [comment]
We definitely need two different libraries for mac and linux.

The static linking for mac works fine (if I use a library built on mac). But the library I built on ubuntu throws a [strange error](https://travis-ci.org/nteract/zmq-prebuilt/jobs/161392493#L363) on travis.

Do you have an idea why this isn't working?

**Comment by minrk** [comment]
Some naïve googling suggests that a missing `-fPIC` in CFLAGS might lead to this.

Do we really want binary builds of static libraries in the source repo? I know the Windows ones are there as a bit of a punt, but I'm surprised at adopting the same workaround on other platforms.

**Comment by lgeiger** [comment]
@minrk Thanks for taking a look! I'll try it.

> Do we really want binary builds of static libraries in the source repo?

I leave this decision up to you and @rgbkrk. The idea behind this is, it would allow us to have a working fallback if no prebuilts are available since the library is included. Or am I missing something?

**Comment by rgbkrk** [comment]
What we really want are binary builds of static libraries as part of the released package, whether on npm or (somehow) as part of the prebuild artifact.

**Comment by minrk** [comment]
I'm a lot more familiar with the Python packaging process, so I know how to include generated products in releases that aren't in repos there, but I don't know the best way for nodejs. It's probably not a huge deal to bundle .a files in source with git-lfs, but it doesn't seem right to me.

**Comment by rgbkrk** [comment]
npm will upload anything that isn't in `.gitignore` and if you want to upload things that you don't ignore for release you have to create a `.npmignore`.

**Comment by lgeiger** [comment]
The idea behind this was to make the fallback work on unix systems. It is superseded by #52

**Pull request closed without merging**
