### PR TITLE
Retry tests on appveyor

### PR DESCRIPTION
**Pull request by lgeiger**
Some tests are timing out randomly. This will retry the testsuite.

Since this is a upstream problem this is the best we can do for now (travis retries as well).

### CODE REVIEW

**Comment by rgbkrk** [comment]
AppVeyor makes that nice and clean.

**Comment by lgeiger** [comment]
I reduced the error timeouts on my machine to see the output of random failing tests. It looks like they're failing because the hardcoded ports are sometimes not available.

I think I open a issue on the upstream repo 😁.

**Comment by rgbkrk** [comment]
`portfinder` to the rescue?

**Comment by lgeiger** [comment]
Yup probably

**Pull request merged**
