### PR TITLE
Update secure token

### PR DESCRIPTION
**Pull request by rgbkrk**

### CODE REVIEW

**Comment by lgeiger** [comment]
I'm not sure if this will work. I think that's powershell syntax?!

**Comment by rgbkrk** [comment]
Oh is this only batch? I pulled it from AppVeyor's docs.

**Comment by lgeiger** [comment]
Yep powershell errored very strange. That's why I opted for batch.

**Comment by rgbkrk** [comment]
Ok, I'll switch it back. While I'm at it, I think I'll cut down on the number of node versions.

**Comment by lgeiger** [comment]
> While I'm at it, I think I'll cut down on the number of node versions.

It deploys only on one travis/appveyor process.

**Comment by rgbkrk** [comment]
> It deploys only on one travis/appveyor process.

I noticed! That's so great that you built that in.

**Pull request merged**
