### PR TITLE
Sync with upstream

### PR DESCRIPTION
**Pull request by lgeiger**
Discovered during #30 that only `lib/index.js` is in sync with upstream.

### CODE REVIEW

**Comment by lgeiger** [comment]
Be careful 😆 
b7e

**Comment by rgbkrk** [comment]
Wow that's a mega sync. I'll use the last release for today's nteract/nteract release since we'll want some time this next week to give this a spin.

**Comment by lgeiger** [comment]
This shouldn't change anything functionality wise. The only changes are in `travis.yml` and the `tests` directory.

**Comment by rgbkrk** [comment]
Ping @minrk for review.

**Comment by rgbkrk** [comment]
Since we made the release yesterday, I think we can merge this and keep going.

**Comment by lgeiger** [comment]
We should probably squash the commits during merging.

**Comment by rgbkrk** [comment]
Squash merged

**Comment by minrk** [comment]
Sorry to be slow, I'm trying to mostly ignore GitHub on the weekend. 👍, thanks @lgeiger!

**Comment by rgbkrk** [comment]
Hey that's ok; glad you enjoy the weekends away from GitHub!

For me at least, weekends and evenings, when the kids are occupied is when I tend to sneak in more coding time.

**Pull request merged**
