### PR TITLE
Dockerize

### PR DESCRIPTION
**Pull request by rgbkrk**
Follow on to #7, incorporating other changes.

### CODE REVIEW

**Comment by rgbkrk** [comment]
This is in happy state and I was able to use the current releases on a clean Mac and in Linux.

## Shipping Linux binaries

```
docker build -t zmqprebuilt .
docker run -it zmqprebuilt prebuild --all -u $GITHUB_TOKEN
```

## Shipping OS X binaries

From a Mac:

```
npm install
npm install -g prebuild
prebuild --all -u $GITHUB_TOKEN
```

**Comment by jdfreder** [comment]
AppVeyor is not happy, is that okay?  Looks like the socket monitor bind is failing on node 5  https://ci.appveyor.com/project/rgbkrk/zmq-prebuilt/build/1.0.39/job/ibjq66k6uitjkxgg#L335

**Comment by rgbkrk** [comment]
It's intermittent and unrelated to the Dockerfile and docker ignore. There are passing builds for this on the other branch.

Effectively, race condition in the original zmq bindings that we haven't fixed yet.

**Comment by rgbkrk** [comment]
Not other branch. I mean the prior PR i opened for this before we fully forked.

**Comment by jdfreder** [comment]
:camel:

**Pull request merged**
